# Generated by Django 4.1 on 2022-09-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
