# Generated by Django 4.1 on 2022-09-28 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'get_latest_by': 'user'},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user_id', 'following_user_id')},
        ),
    ]
