# Generated by Django 4.1 on 2022-11-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'get_latest_by': 'user', 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='?', max_length=200),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='users_profile',
        ),
    ]
